// Generated by Xata Codegen 0.30.1. Please do not edit.
import { buildClient } from "@xata.io/client";
import type {
  BaseClientOptions,
  SchemaInference,
  XataRecord,
} from "@xata.io/client";

const tables = [
  {
    name: "Amjad Hossain",
    checkConstraints: {
      Rahil_xata_id_length_xata_id: {
        name: "Rahil_xata_id_length_xata_id",
        columns: ["xata_id"],
        definition: "CHECK ((length(xata_id) < 256))",
      },
    },
    foreignKeys: {
      subject_id_link: {
        name: "subject_id_link",
        columns: ["subject_id"],
        referencedTable: "subjects",
        referencedColumns: ["xata_id"],
        onDelete: "SET NULL",
      },
      teach_id_link: {
        name: "teach_id_link",
        columns: ["teach_id"],
        referencedTable: "teachers",
        referencedColumns: ["teach_id"],
        onDelete: "SET NULL",
      },
    },
    primaryKey: [],
    uniqueConstraints: {
      _pgroll_new_Rahil_xata_id_key: {
        name: "_pgroll_new_Rahil_xata_id_key",
        columns: ["xata_id"],
      },
    },
    columns: [
      {
        name: "day",
        type: "text",
        notNull: false,
        unique: false,
        defaultValue: null,
        comment: "",
      },
      {
        name: "period",
        type: "int",
        notNull: false,
        unique: false,
        defaultValue: null,
        comment: "",
      },
      {
        name: "subject_id",
        type: "link",
        link: { table: "subjects" },
        notNull: false,
        unique: false,
        defaultValue: null,
        comment: '{"xata.link":"subjects"}',
      },
      {
        name: "teach_id",
        type: "link",
        link: { table: "teachers" },
        notNull: false,
        unique: false,
        defaultValue: null,
        comment: '{"xata.link":"teachers"}',
      },
      {
        name: "xata_createdat",
        type: "datetime",
        notNull: true,
        unique: false,
        defaultValue: "now()",
        comment: "",
      },
      {
        name: "xata_id",
        type: "text",
        notNull: true,
        unique: true,
        defaultValue: "('rec_'::text || (xata_private.xid())::text)",
        comment: "",
      },
      {
        name: "xata_updatedat",
        type: "datetime",
        notNull: true,
        unique: false,
        defaultValue: "now()",
        comment: "",
      },
      {
        name: "xata_version",
        type: "int",
        notNull: true,
        unique: false,
        defaultValue: "0",
        comment: "",
      },
    ],
  },
  {
    name: "Md. Rasel Ahmed",
    checkConstraints: {
      Raid_xata_id_length_xata_id: {
        name: "Raid_xata_id_length_xata_id",
        columns: ["xata_id"],
        definition: "CHECK ((length(xata_id) < 256))",
      },
    },
    foreignKeys: {
      subject_id_link: {
        name: "subject_id_link",
        columns: ["subject_id"],
        referencedTable: "subjects",
        referencedColumns: ["xata_id"],
        onDelete: "SET NULL",
      },
      teach_id_link: {
        name: "teach_id_link",
        columns: ["teach_id"],
        referencedTable: "teachers",
        referencedColumns: ["teach_id"],
        onDelete: "SET NULL",
      },
    },
    primaryKey: [],
    uniqueConstraints: {
      _pgroll_new_Raid_xata_id_key: {
        name: "_pgroll_new_Raid_xata_id_key",
        columns: ["xata_id"],
      },
    },
    columns: [
      {
        name: "day",
        type: "text",
        notNull: false,
        unique: false,
        defaultValue: null,
        comment: "",
      },
      {
        name: "period",
        type: "int",
        notNull: false,
        unique: false,
        defaultValue: null,
        comment: "",
      },
      {
        name: "subject_id",
        type: "link",
        link: { table: "subjects" },
        notNull: false,
        unique: false,
        defaultValue: null,
        comment: '{"xata.link":"subjects"}',
      },
      {
        name: "teach_id",
        type: "link",
        link: { table: "teachers" },
        notNull: false,
        unique: false,
        defaultValue: null,
        comment: '{"xata.link":"teachers"}',
      },
      {
        name: "xata_createdat",
        type: "datetime",
        notNull: true,
        unique: false,
        defaultValue: "now()",
        comment: "",
      },
      {
        name: "xata_id",
        type: "text",
        notNull: true,
        unique: true,
        defaultValue: "('rec_'::text || (xata_private.xid())::text)",
        comment: "",
      },
      {
        name: "xata_updatedat",
        type: "datetime",
        notNull: true,
        unique: false,
        defaultValue: "now()",
        comment: "",
      },
      {
        name: "xata_version",
        type: "int",
        notNull: true,
        unique: false,
        defaultValue: "0",
        comment: "",
      },
    ],
  },
  {
    name: "Shahana Sultana",
    checkConstraints: {
      Aarsh_xata_id_length_xata_id: {
        name: "Aarsh_xata_id_length_xata_id",
        columns: ["xata_id"],
        definition: "CHECK ((length(xata_id) < 256))",
      },
    },
    foreignKeys: {
      subject_id_link: {
        name: "subject_id_link",
        columns: ["subject_id"],
        referencedTable: "subjects",
        referencedColumns: ["xata_id"],
        onDelete: "SET NULL",
      },
      teach_id_link: {
        name: "teach_id_link",
        columns: ["teach_id"],
        referencedTable: "teachers",
        referencedColumns: ["teach_id"],
        onDelete: "SET NULL",
      },
    },
    primaryKey: [],
    uniqueConstraints: {
      _pgroll_new_Aarsh_xata_id_key: {
        name: "_pgroll_new_Aarsh_xata_id_key",
        columns: ["xata_id"],
      },
    },
    columns: [
      {
        name: "day",
        type: "text",
        notNull: false,
        unique: false,
        defaultValue: null,
        comment: "",
      },
      {
        name: "period",
        type: "int",
        notNull: false,
        unique: false,
        defaultValue: null,
        comment: "",
      },
      {
        name: "subject_id",
        type: "link",
        link: { table: "subjects" },
        notNull: false,
        unique: false,
        defaultValue: null,
        comment: '{"xata.link":"subjects"}',
      },
      {
        name: "teach_id",
        type: "link",
        link: { table: "teachers" },
        notNull: false,
        unique: false,
        defaultValue: null,
        comment: '{"xata.link":"teachers"}',
      },
      {
        name: "xata_createdat",
        type: "datetime",
        notNull: true,
        unique: false,
        defaultValue: "now()",
        comment: "",
      },
      {
        name: "xata_id",
        type: "text",
        notNull: true,
        unique: true,
        defaultValue: "('rec_'::text || (xata_private.xid())::text)",
        comment: "",
      },
      {
        name: "xata_updatedat",
        type: "datetime",
        notNull: true,
        unique: false,
        defaultValue: "now()",
        comment: "",
      },
      {
        name: "xata_version",
        type: "int",
        notNull: true,
        unique: false,
        defaultValue: "0",
        comment: "",
      },
    ],
  },
  {
    name: "subjects",
    checkConstraints: {
      subject_xata_id_length_xata_id: {
        name: "subject_xata_id_length_xata_id",
        columns: ["xata_id"],
        definition: "CHECK ((length(xata_id) < 256))",
      },
    },
    foreignKeys: {},
    primaryKey: [],
    uniqueConstraints: {
      _pgroll_new_subject_xata_id_key: {
        name: "_pgroll_new_subject_xata_id_key",
        columns: ["xata_id"],
      },
    },
    columns: [
      {
        name: "sub_name",
        type: "text",
        notNull: true,
        unique: false,
        defaultValue: null,
        comment: "",
      },
      {
        name: "xata_createdat",
        type: "datetime",
        notNull: true,
        unique: false,
        defaultValue: "now()",
        comment: "",
      },
      {
        name: "xata_id",
        type: "text",
        notNull: true,
        unique: true,
        defaultValue: "('rec_'::text || (xata_private.xid())::text)",
        comment: "",
      },
      {
        name: "xata_updatedat",
        type: "datetime",
        notNull: true,
        unique: false,
        defaultValue: "now()",
        comment: "",
      },
      {
        name: "xata_version",
        type: "int",
        notNull: true,
        unique: false,
        defaultValue: "0",
        comment: "",
      },
    ],
  },
  {
    name: "teachers",
    checkConstraints: {
      teachers_xata_id_length_xata_id: {
        name: "teachers_xata_id_length_xata_id",
        columns: ["xata_id"],
        definition: "CHECK ((length(xata_id) < 256))",
      },
    },
    foreignKeys: {},
    primaryKey: [],
    uniqueConstraints: {
      _pgroll_new_teachers_xata_id_key: {
        name: "_pgroll_new_teachers_xata_id_key",
        columns: ["xata_id"],
      },
      teachers__pgroll_new_email_key: {
        name: "teachers__pgroll_new_email_key",
        columns: ["email"],
      },
      teachers__pgroll_new_name_key: {
        name: "teachers__pgroll_new_name_key",
        columns: ["name"],
      },
      teachers__pgroll_new_teach_id_key: {
        name: "teachers__pgroll_new_teach_id_key",
        columns: ["teach_id"],
      },
    },
    columns: [
      {
        name: "email",
        type: "text",
        notNull: true,
        unique: true,
        defaultValue: null,
        comment: "",
      },
      {
        name: "name",
        type: "text",
        notNull: true,
        unique: true,
        defaultValue: null,
        comment: "",
      },
      {
        name: "teach_id",
        type: "text",
        notNull: true,
        unique: true,
        defaultValue: null,
        comment: "",
      },
      {
        name: "xata_createdat",
        type: "datetime",
        notNull: true,
        unique: false,
        defaultValue: "now()",
        comment: "",
      },
      {
        name: "xata_id",
        type: "text",
        notNull: true,
        unique: true,
        defaultValue: "('rec_'::text || (xata_private.xid())::text)",
        comment: "",
      },
      {
        name: "xata_updatedat",
        type: "datetime",
        notNull: true,
        unique: false,
        defaultValue: "now()",
        comment: "",
      },
      {
        name: "xata_version",
        type: "int",
        notNull: true,
        unique: false,
        defaultValue: "0",
        comment: "",
      },
    ],
  },
  {
    name: "users",
    checkConstraints: {
      users_xata_id_length_xata_id: {
        name: "users_xata_id_length_xata_id",
        columns: ["xata_id"],
        definition: "CHECK ((length(xata_id) < 256))",
      },
    },
    foreignKeys: {},
    primaryKey: [],
    uniqueConstraints: {
      _pgroll_new_users_xata_id_key: {
        name: "_pgroll_new_users_xata_id_key",
        columns: ["xata_id"],
      },
      users__pgroll_new_email_key: {
        name: "users__pgroll_new_email_key",
        columns: ["email"],
      },
    },
    columns: [
      {
        name: "email",
        type: "text",
        notNull: true,
        unique: true,
        defaultValue: null,
        comment: "",
      },
      {
        name: "name",
        type: "text",
        notNull: true,
        unique: false,
        defaultValue: null,
        comment: "",
      },
      {
        name: "password",
        type: "text",
        notNull: true,
        unique: false,
        defaultValue: null,
        comment: "",
      },
      {
        name: "xata_createdat",
        type: "datetime",
        notNull: true,
        unique: false,
        defaultValue: "now()",
        comment: "",
      },
      {
        name: "xata_id",
        type: "text",
        notNull: true,
        unique: true,
        defaultValue: "('rec_'::text || (xata_private.xid())::text)",
        comment: "",
      },
      {
        name: "xata_updatedat",
        type: "datetime",
        notNull: true,
        unique: false,
        defaultValue: "now()",
        comment: "",
      },
      {
        name: "xata_version",
        type: "int",
        notNull: true,
        unique: false,
        defaultValue: "0",
        comment: "",
      },
    ],
  },
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type AmjadHossain = InferredTypes["Amjad Hossain"];
export type AmjadHossainRecord = AmjadHossain & XataRecord;

export type MdRaselAhmed = InferredTypes["Md. Rasel Ahmed"];
export type MdRaselAhmedRecord = MdRaselAhmed & XataRecord;

export type ShahanaSultana = InferredTypes["Shahana Sultana"];
export type ShahanaSultanaRecord = ShahanaSultana & XataRecord;

export type Subjects = InferredTypes["subjects"];
export type SubjectsRecord = Subjects & XataRecord;

export type Teachers = InferredTypes["teachers"];
export type TeachersRecord = Teachers & XataRecord;

export type Users = InferredTypes["users"];
export type UsersRecord = Users & XataRecord;

export type DatabaseSchema = {
  "Amjad Hossain": AmjadHossainRecord;
  "Md. Rasel Ahmed": MdRaselAhmedRecord;
  "Shahana Sultana": ShahanaSultanaRecord;
  subjects: SubjectsRecord;
  teachers: TeachersRecord;
  users: UsersRecord;
};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL:
    "https://Tariq-Hassan-s-workspace-5iqs1u.us-east-1.xata.sh/db/Auth",
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};
